- name: Install Apache
  yum:
    name: httpd
    state: present

- name: Change file ownership, group and permissions
  file:
    path: "{{ doc_root }}"
    state: directory
    owner: www-data
    group: www-data

- name: Set up HTML file
  copy:
    src: index.html
    dest: "{{ doc_root }}/index.html"
    owner: www-data
    group: www-data
    mode: 0644

- name: Set up Apache virtual host file
  template:
    src: vhost.tpl
    dest: /etc/apache2/sites-available/000-default.conf
  notify:
    restart_apache