- name: Install Apache
  yum:
    name: httpd
    state: present

- name: Change file ownership, group and permissions
  file:
    path: "{{ doc_root }}"
    state: directory
    owner: www-data
    group: www-data

- name: Set up HTML file
  copy:
    src: index.html
    dest: "{{ doc_root }}/index.html"
    owner: www-data
    group: www-data
    mode: 0644

- name: Change the port
  lineinfile:
    path: /etc/httpd/conf/httpd.conf
    regexp: '^Listen '
    insertafter: '^#Listen '
    line: 'Listen {{apache_port}}'
  notify:
    restart_apache